import type { Conversation, Listing, Message, Seller, Review } from "./types";

const img = (id: string, w = 900) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

const av = (name: string) =>
  `https://ui-avatars.com/api/?background=0D9488&color=fff&name=${encodeURIComponent(name)}`;

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();

const dotReview = (
  id: string,
  author: string,
  rating: number,
  days: number,
  text: string
): Review => ({
  id,
  author,
  authorAvatar: av(author),
  rating,
  date: daysAgo(days),
  text,
});

export const SELLERS: Seller[] = [
  {
    id: "s1",
    name: "Ayan Auto Djibouti",
    username: "ayan_auto",
    avatar: av("Ayan Auto"),
    location: "Balbala, Djibouti",
    verified: true,
    business: true,
    rating: 4.9,
    reviewCount: 184,
    joined: daysAgo(920),
    bio: "Official importer and dealer of premium Japanese and European cars in Djibouti. Financed and inspected vehicles with full history.",
    phone: "+253 77 12 34 56",
    languages: ["fr", "so", "en"],
    featured: true,
    skills: ["Vehicles", "Financing", "Inspections"],
    followers: 2800,
    listingsCount: 22,
  },
  {
    id: "s2",
    name: "Horizon Immobilier",
    username: "horizon_immo",
    avatar: av("Horizon Immobilier"),
    location: "Heron, Djibouti",
    verified: true,
    business: true,
    rating: 4.8,
    reviewCount: 96,
    joined: daysAgo(640),
    bio: "Full-service real-estate agency for Djibouti City. Sale, rental and property management for homes, offices and commercial spaces.",
    phone: "+253 77 98 76 54",
    languages: ["fr", "ar", "en"],
    featured: true,
    skills: ["Real estate", "Rental", "Management"],
    followers: 1430,
    listingsCount: 31,
  },
  {
    id: "s3",
    name: "Hodan Ahmed",
    username: "hodan",
    avatar: av("Hodan Ahmed"),
    location: "Tadjourah",
    verified: true,
    rating: 4.9,
    reviewCount: 74,
    joined: daysAgo(410),
    bio: "Trusted private seller of electronics, phones and home appliances. Fast delivery across Djibouti.",
    phone: "+253 77 45 12 90",
    languages: ["so", "fr"],
    featured: true,
    skills: ["Electronics", "Phones", "Appliances"],
    followers: 940,
    listingsCount: 16,
  },
  {
    id: "s4",
    name: "Balbala Motors",
    username: "balbala_motors",
    avatar: av("Balbala Motors"),
    location: "Balbala",
    verified: false,
    rating: 4.4,
    reviewCount: 31,
    joined: daysAgo(230),
    bio: "Budget-friendly used cars, motorcycles and spare parts in Balbala.",
    phone: "+253 77 22 11 33",
    languages: ["fr", "so"],
    skills: ["Cars", "Motorcycles", "Spare parts"],
    followers: 310,
    listingsCount: 12,
  },
  {
    id: "s5",
    name: "Rania Style",
    username: "rania_style",
    avatar: av("Rania Style"),
    location: "Djibouti City Centre",
    verified: true,
    rating: 4.7,
    reviewCount: 58,
    joined: daysAgo(300),
    bio: "Curated fashion, watches and accessories imported from Dubai and Paris.",
    phone: "+253 77 33 44 55",
    languages: ["fr", "ar"],
    skills: ["Fashion", "Watches", "Accessories"],
    followers: 760,
    listingsCount: 19,
  },
  {
    id: "s6",
    name: "Moussa Construction Services",
    username: "moussa_construction",
    avatar: av("Moussa Construction"),
    location: "Djibouti City",
    verified: true,
    business: true,
    rating: 4.8,
    reviewCount: 42,
    joined: daysAgo(540),
    bio: "Construction, renovation, electrical and plumbing services. Licensed crews and project management.",
    phone: "+253 77 55 66 77",
    languages: ["fr", "so", "ar"],
    skills: ["Construction", "Electricity", "Plumbing", "Painting"],
    followers: 510,
    listingsCount: 9,
  },
  {
    id: "s7",
    name: "Safiya Farm Supply",
    username: "safiya_farm",
    avatar: av("Safiya Farm"),
    location: "Ali Sabieh",
    verified: true,
    rating: 4.6,
    reviewCount: 27,
    joined: daysAgo(180),
    bio: "Agricultural equipment, animals and tools for farmers across Djibouti.",
    phone: "+253 77 88 99 00",
    languages: ["so", "fr"],
    skills: ["Agriculture", "Equipment", "Animals"],
    followers: 240,
    listingsCount: 8,
  },
  {
    id: "s8",
    name: "Absar Freelance Studio",
    username: "absar_studio",
    avatar: av("Absar Studio"),
    location: "Remote / Djibouti",
    verified: true,
    rating: 5.0,
    reviewCount: 19,
    joined: daysAgo(150),
    bio: "Designer, developer and digital marketer. Branding, websites and social media for local businesses.",
    phone: "+253 77 10 20 30",
    languages: ["fr", "en", "so"],
    skills: ["Design", "Web", "Marketing"],
    followers: 830,
    listingsCount: 6,
  },
];

export const LISTINGS: Listing[] = [
  // ---------- Vehicles ----------
  {
    id: "l1",
    title: "Toyota Land Cruiser Prado 2019",
    description:
      "Excellent condition 2019 Toyota Land Cruiser Prado, 2.8L diesel, 4x4. Single owner, full service history, new tires, sunroof, leather interior, reverse camera and cruise control. Ideal for family and desert travel. Financing available.",
    price: 12500000,
    category: "vehicles",
    kind: "vehicles",
    images: [
      { id: "i1a", url: img("1502877338535-766e1452684a", 1100), alt: "Toyota Land Cruiser Prado front" },
      { id: "i1b", url: img("1519641471654-76ce0107ad1b", 900), alt: "Prado side" },
      { id: "i1c", url: img("1533473359331-0135ef1b58bf", 900), alt: "Prado interior" },
    ],
    location: "Balbala, Djibouti",
    condition: "used",
    sellerId: "s1",
    createdAt: daysAgo(1),
    featured: true,
    views: 1240,
    favorites: 89,
    tags: ["4x4", "diesel", "family", "financing"],
    brand: "Toyota",
    model: "Land Cruiser Prado",
    year: 2019,
    mileage: 48000,
    fuel: "diesel",
    transmission: "automatic",
    color: "White",
    reviews: [
      dotReview("r1", "Fatouma", 5, 4, "Dealer was transparent, car exactly as described."),
      dotReview("r2", "Ismail", 5, 12, "Fast financing and friendly follow-up. Highly recommend."),
    ],
    status: "active",
  },
  {
    id: "l2",
    title: "Honda CR-V 2021 – Automatic",
    description:
      "Low mileage Honda CR-V, 1.5L turbo, automatic, leather seats, panoramic sunroof, lane assist and Apple CarPlay. Perfect city SUV with great fuel economy.",
    price: 9800000,
    category: "vehicles",
    kind: "vehicles",
    images: [
      { id: "i2a", url: img("1568844293986-8d0400bd4745", 1100), alt: "Honda CR-V" },
      { id: "i2b", url: img("1518987048-93e29699e79a", 900), alt: "Car interior" },
    ],
    location: "Heron, Djibouti",
    condition: "used",
    sellerId: "s1",
    createdAt: daysAgo(2),
    featured: true,
    views: 900,
    favorites: 61,
    tags: ["SUV", "automatic", "low mileage", "city"],
    brand: "Honda",
    model: "CR-V",
    year: 2021,
    mileage: 21000,
    fuel: "petrol",
    transmission: "automatic",
    color: "Silver",
    reviews: [dotReview("r3", "Ali", 5, 2, "Great condition and honest price.")],
    status: "active",
  },
  {
    id: "l3",
    title: "Toyota Corolla 2016 – Economy Car",
    description:
      "Reliable Toyota Corolla, petrol, manual, 112,000 km. Clean interior, cold AC, new battery and brakes. Affordable first car or taxi. Cash price negotiable.",
    price: 4200000,
    category: "vehicles",
    kind: "vehicles",
    images: [
      { id: "i3a", url: img("1590362891991-f776e747a588", 1100), alt: "Toyota Corolla" },
      { id: "i3b", url: img("1494976388531-d1058494cdd8", 900), alt: "Muscle car" },
    ],
    location: "Balbala",
    condition: "used",
    sellerId: "s4",
    createdAt: daysAgo(4),
    views: 640,
    favorites: 34,
    tags: ["economy", "taxi", "reliable"],
    brand: "Toyota",
    model: "Corolla",
    year: 2016,
    mileage: 112000,
    fuel: "petrol",
    transmission: "manual",
    color: "Silver",
    reviews: [],
    status: "active",
  },
  {
    id: "l4",
    title: "Mercedes-Benz C220 – Premium Sedan",
    description:
      "2018 C220 AMG line, diesel, automatic, 58,000 km. Full options, ambient lighting, navigation, memory seats, rear parking camera. Imported, clean history.",
    price: 14800000,
    category: "vehicles",
    kind: "vehicles",
    images: [
      { id: "i4a", url: img("1552519507-da3b142c6e3d", 1100), alt: "Mercedes C220" },
      { id: "i4b", url: img("1503376780353-7e6692767b70", 900), alt: "Sport car" },
    ],
    location: "Djibouti City Centre",
    condition: "used",
    sellerId: "s4",
    createdAt: daysAgo(6),
    featured: true,
    views: 2100,
    favorites: 140,
    tags: ["luxury", "automatic", "diesel", "imported"],
    brand: "Mercedes-Benz",
    model: "C220",
    year: 2018,
    mileage: 58000,
    fuel: "diesel",
    transmission: "automatic",
    color: "Black",
    reviews: [
      dotReview("r4", "Yusuf", 5, 3, "Premium car, seller made everything easy."),
    ],
    status: "active",
  },
  {
    id: "l5",
    title: "Yamaha Motorcycle 150cc",
    description:
      "Like-new Yamaha 150cc motorcycle, ideal for city delivery or daily commuting. Low mileage, new tires, clean title and documents.",
    price: 850000,
    category: "vehicles",
    kind: "vehicles",
    images: [{ id: "i5a", url: img("1558981403-c5f9899a28bc", 1100), alt: "Yamaha motorcycle" }],
    location: "Balbala",
    condition: "used",
    sellerId: "s5",
    createdAt: daysAgo(3),
    views: 410,
    favorites: 22,
    tags: ["motorcycle", "delivery", "150cc"],
    brand: "Yamaha",
    model: "150cc",
    year: 2022,
    mileage: 5200,
    fuel: "petrol",
    transmission: "manual",
    color: "Blue",
    reviews: [],
    status: "active",
  },
  {
    id: "l6",
    title: "Rent a Land Cruiser – 4x4 with Driver",
    description:
      "Daily 4x4 rental with professional driver for tours, business trips and events in Djibouti. Includes fuel first 100 km. Airport pick-up available.",
    price: 25000,
    priceLabel: "per day",
    category: "vehicles",
    kind: "rentals",
    images: [
      { id: "i6a", url: img("1502877338535-766e1452684a", 1100), alt: "Rental Land Cruiser" },
      { id: "i6b", url: img("1533473359331-0135ef1b58bf", 900), alt: "Interior" },
    ],
    location: "Djibouti City",
    condition: "for-rent",
    sellerId: "s1",
    createdAt: daysAgo(1),
    views: 780,
    favorites: 53,
    tags: ["rental", "4x4", "driver"],
    brand: "Toyota",
    model: "Land Cruiser",
    year: 2022,
    fuel: "diesel",
    transmission: "automatic",
    color: "White",
    rental: { perDay: 25000, periods: "day" },
    reviews: [dotReview("r5", "Nora", 5, 5, "Excellent driver and clean car.")],
    status: "active",
  },
  {
    id: "l7",
    title: "Toyota HiAce Minibus – 15 Seats",
    description:
      "Commercial Toyota HiAce minibus for sale. Perfect for taxi service, school transport or hotel pickups. Diesel, manual, well maintained.",
    price: 7600000,
    category: "vehicles",
    kind: "vehicles",
    images: [{ id: "i7a", url: img("1601584115197-04ecc0da31d7", 1100), alt: "Toyota HiAce" }],
    location: "Djibouti City",
    condition: "used",
    sellerId: "s4",
    createdAt: daysAgo(8),
    views: 500,
    favorites: 30,
    tags: ["commercial", "minibus", "taxi"],
    brand: "Toyota",
    model: "HiAce",
    year: 2017,
    mileage: 145000,
    fuel: "diesel",
    transmission: "manual",
    color: "White",
    reviews: [],
    status: "active",
  },
  {
    id: "l8",
    title: "Nissan Patrol 2020 – 4x4 Leather",
    description:
      "Powerful 2020 Nissan Patrol, V6 petrol, 4x4. Full leather, navigation, sunroof and 7 seats. Perfect for desert expeditions and official use.",
    price: 16500000,
    category: "vehicles",
    kind: "vehicles",
    images: [{ id: "i8a", url: img("1518987048-93e29699e79a", 1100), alt: "Nissan Patrol" }],
    location: "Heron, Djibouti",
    condition: "used",
    sellerId: "s1",
    createdAt: daysAgo(10),
    views: 950,
    favorites: 70,
    tags: ["4x4", "luxury", "desert"],
    brand: "Nissan",
    model: "Patrol",
    year: 2020,
    mileage: 64000,
    fuel: "petrol",
    transmission: "automatic",
    color: "Grey",
    reviews: [],
    status: "active",
  },

  // ---------- Real Estate ----------
  {
    id: "l9",
    title: "Modern Villa for Sale – Heron District",
    description:
      "Contemporary 5-bedroom villa with private garden, swimming pool, garage for 2 cars and rooftop terrace. Located in a quiet, secure residential neighbourhood. Built 2021, ready to move in.",
    price: 95000000,
    category: "real-estate",
    kind: "real-estate",
    images: [
      { id: "i9a", url: img("1568605114967-8130f3a36994", 1100), alt: "Modern villa exterior" },
      { id: "i9b", url: img("1600585154340-be6161a56a0c", 900), alt: "Villa living room" },
      { id: "i9c", url: img("1600607687939-ce8a6c25118c", 900), alt: "Villa interior" },
    ],
    location: "Heron, Djibouti",
    condition: "new",
    sellerId: "s2",
    createdAt: daysAgo(2),
    featured: true,
    views: 1800,
    favorites: 210,
    tags: ["villa", "pool", "garden", "secure"],
    bedrooms: 5,
    bathrooms: 4,
    area: 420,
    yearBuilt: 2021,
    reviews: [],
    status: "active",
  },
  {
    id: "l10",
    title: "Apartment for Rent – Djibouti City Centre",
    description:
      "Bright 3-bedroom apartment near the city centre. Fully furnished, two bathrooms, large balcony, internet and water included. Available from next month.",
    price: 180000,
    priceLabel: "per month",
    category: "real-estate",
    kind: "rentals",
    images: [
      { id: "i10a", url: img("1522708323590-d24dbb6b0267", 1100), alt: "Modern apartment living room" },
      { id: "i10b", url: img("1567767292278-a4f21aa2d36e", 900), alt: "Apartment bedroom" },
    ],
    location: "Djibouti City Centre",
    condition: "for-rent",
    sellerId: "s2",
    createdAt: daysAgo(1),
    featured: true,
    views: 1420,
    favorites: 160,
    tags: ["apartment", "furnished", "city centre"],
    bedrooms: 3,
    bathrooms: 2,
    area: 140,
    yearBuilt: 2018,
    rental: { perMonth: 180000, periods: "month" },
    reviews: [dotReview("r6", "Khadija", 5, 3, "Very clean and centrally located. Recommended.")],
    status: "active",
  },
  {
    id: "l11",
    title: "Commercial Office Space – Sheik Ismail",
    description:
      "Premium office space on the second floor, 220 m² with shared reception and parking. Ideal for banks, NGOs, telecom or import/export companies. Rent negotiable.",
    price: 600000,
    priceLabel: "per month",
    category: "real-estate",
    kind: "rentals",
    images: [
      { id: "i11a", url: img("1497366216548-37526070297c", 1100), alt: "Office space" },
      { id: "i11b", url: img("1497366811353-6870744d04b2", 900), alt: "Office interior" },
    ],
    location: "Sheik Ismail, Djibouti",
    condition: "for-rent",
    sellerId: "s2",
    createdAt: daysAgo(5),
    views: 720,
    favorites: 45,
    tags: ["office", "commercial", "parking"],
    bedrooms: 0,
    bathrooms: 2,
    area: 220,
    yearBuilt: 2016,
    rental: { perMonth: 600000, periods: "month" },
    reviews: [],
    status: "active",
  },
  {
    id: "l12",
    title: "Residential Land – Balbala, 400 m²",
    description:
      "Flat plot of residential land with water and electricity nearby. Clear title, ready for construction. Perfect for a villa or a small apartment building.",
    price: 18000000,
    category: "real-estate",
    kind: "real-estate",
    images: [{ id: "i12a", url: img("1500382017468-9049fed747ef", 1100), alt: "Residential land" }],
    location: "Balbala, Djibouti",
    condition: "new",
    sellerId: "s2",
    createdAt: daysAgo(9),
    views: 830,
    favorites: 55,
    tags: ["land", "build", "balbala"],
    bedrooms: 0,
    bathrooms: 0,
    area: 400,
    reviews: [],
    status: "active",
  },
  {
    id: "l13",
    title: "Studio Apartment – Tadjourah",
    description:
      "Cozy furnished studio close to the beach. Air conditioning, kitchenette and private bathroom. Short or long-term rental available.",
    price: 95000,
    priceLabel: "per month",
    category: "real-estate",
    kind: "rentals",
    images: [{ id: "i13a", url: img("1505693416388-ac5ce068fe85", 1100), alt: "Studio bedroom" }],
    location: "Tadjourah",
    condition: "for-rent",
    sellerId: "s3",
    createdAt: daysAgo(7),
    views: 590,
    favorites: 40,
    tags: ["studio", "furnished", "beach"],
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    rental: { perMonth: 95000, periods: "month" },
    reviews: [],
    status: "active",
  },
  {
    id: "l14",
    title: "Retail Shop for Rent – Marché Central",
    description:
      "High-footfall retail unit in the central market area. 50 m², good visibility, storage room, water and electricity. Suitable for clothing, phones or food shop.",
    price: 150000,
    priceLabel: "per month",
    category: "real-estate",
    kind: "rentals",
    images: [{ id: "i14a", url: img("1441986300917-64674bd600d8", 1100), alt: "Retail shop" }],
    location: "Djibouti City Centre",
    condition: "for-rent",
    sellerId: "s2",
    createdAt: daysAgo(11),
    views: 460,
    favorites: 28,
    tags: ["shop", "retail", "market"],
    bedrooms: 0,
    bathrooms: 1,
    area: 50,
    rental: { perMonth: 150000, periods: "month" },
    reviews: [],
    status: "active",
  },

  // ---------- Electronics ----------
  {
    id: "l15",
    title: "iPhone 14 Pro 256GB – Brand New",
    description:
      "Brand new, sealed iPhone 14 Pro in Deep Purple, 256GB. Global version, 1-year warranty. Includes cable and box. Available in Djibouti City.",
    price: 320000,
    category: "electronics",
    kind: "products",
    images: [{ id: "i15a", url: img("1511707171634-5f897ff02aa9", 1100), alt: "iPhone 14 Pro" }],
    location: "Djibouti City Centre",
    condition: "new",
    sellerId: "s3",
    createdAt: daysAgo(0),
    featured: true,
    views: 2100,
    favorites: 180,
    tags: ["iphone", "phone", "sealed"],
    reviews: [
      dotReview("r7", "Hawa", 5, 1, "Authentic product and fast delivery."),
    ],
    status: "active",
  },
  {
    id: "l16",
    title: "MacBook Air M2 – 13 inch",
    description:
      "MacBook Air M2, 8GB RAM, 256GB SSD, Space Grey. Excellent condition, battery 96%, used for 8 months. Fast and lightweight for work and studies.",
    price: 520000,
    category: "electronics",
    kind: "products",
    images: [{ id: "i16a", url: img("1496181133206-80ce9b88a853", 1100), alt: "MacBook Air" }],
    location: "Djibouti City",
    condition: "used",
    sellerId: "s3",
    createdAt: daysAgo(2),
    views: 1300,
    favorites: 110,
    tags: ["laptop", "macbook", "M2"],
    reviews: [],
    status: "active",
  },
  {
    id: "l17",
    title: "Samsung 55\" Smart TV – 4K",
    description:
      "Samsung Crystal UHD 55\" smart TV, 4K, HDR, Netflix and YouTube built in. Like new, with remote and box. Great for family and football nights.",
    price: 190000,
    category: "electronics",
    kind: "products",
    images: [{ id: "i17a", url: img("1593784991095-a205069470b6", 1100), alt: "Samsung smart TV" }],
    location: "Balbala",
    condition: "used",
    sellerId: "s3",
    createdAt: daysAgo(5),
    views: 940,
    favorites: 66,
    tags: ["tv", "4k", "smart"],
    reviews: [],
    status: "active",
  },
  {
    id: "l18",
    title: "Canon EOS 200D DSLR – Full Kit",
    description:
      "Canon EOS 200D with 18-55mm lens, bag, 64GB SD card and battery charger. Used lightly for photography and videography. Great starter camera.",
    price: 240000,
    category: "electronics",
    kind: "products",
    images: [{ id: "i18a", url: img("1516035069371-29a1b244cc32", 1100), alt: "Canon DSLR camera" }],
    location: "Heron, Djibouti",
    condition: "used",
    sellerId: "s3",
    createdAt: daysAgo(4),
    views: 680,
    favorites: 38,
    tags: ["camera", "dslr", "photography"],
    reviews: [],
    status: "active",
  },
  {
    id: "l19",
    title: "PS5 Console – DualSense Bundle",
    description:
      "PlayStation 5 disc edition with one DualSense controller. Barely used, works perfectly, comes with original box. Ready for games and entertainment.",
    price: 380000,
    category: "electronics",
    kind: "products",
    images: [{ id: "i19a", url: img("1550745165-9bc0b252726f", 1100), alt: "PS5 console" }],
    location: "Djibouti City Centre",
    condition: "used",
    sellerId: "s8",
    createdAt: daysAgo(3),
    views: 1150,
    favorites: 95,
    tags: ["gaming", "ps5", "console"],
    reviews: [],
    status: "active",
  },
  {
    id: "l20",
    title: "Sony Wireless Headphones – WH-1000XM4",
    description:
      "Premium Sony headphones with active noise cancellation, 30h battery, carrying case and cable. Excellent sound for calls, travel and music.",
    price: 98000,
    category: "electronics",
    kind: "products",
    images: [{ id: "i20a", url: img("1505740420928-5e560c06d30e", 1100), alt: "Sony wireless headphones" }],
    location: "Djibouti City",
    condition: "used",
    sellerId: "s3",
    createdAt: daysAgo(6),
    views: 720,
    favorites: 52,
    tags: ["headphones", "sony", "noise-cancelling"],
    reviews: [],
    status: "active",
  },

  // ---------- Buy & Sell / Home / Fashion ----------
  {
    id: "l21",
    title: "Luxury Sofa Set – 7 Seater (New)",
    description:
      "Contemporary L-shaped sofa set with chaise, coffee table and rug. Fabric, removable covers, strong frame. Seats 7. Pickup near city centre.",
    price: 260000,
    category: "buy-sell",
    kind: "products",
    images: [{ id: "i21a", url: img("1567538096630-e0c55bd6374c", 1100), alt: "Luxury sofa set" }],
    location: "Djibouti City Centre",
    condition: "new",
    sellerId: "s3",
    createdAt: daysAgo(2),
    views: 880,
    favorites: 74,
    tags: ["furniture", "sofa", "home"],
    reviews: [],
    status: "active",
  },
  {
    id: "l22",
    title: "Samsung Washing Machine – 8kg",
    description:
      "Samsung front-load washing machine, 8kg, 1200 rpm, inverter motor. Used for one year, in perfect working condition. Great for families.",
    price: 140000,
    category: "buy-sell",
    kind: "products",
    images: [{ id: "i22a", url: img("1626806787461-102c1bfaaea1", 1100), alt: "Washing machine" }],
    location: "Balbala",
    condition: "used",
    sellerId: "s3",
    createdAt: daysAgo(8),
    views: 640,
    favorites: 41,
    tags: ["appliance", "washing machine", "home"],
    reviews: [],
    status: "active",
  },
  {
    id: "l23",
    title: "Rolex-style Automatic Watch – Men",
    description:
      "Elegant automatic watch, stainless steel, sapphire glass, water resistant. Imported from Dubai. Box and warranty included.",
    price: 75000,
    category: "buy-sell",
    kind: "products",
    images: [{ id: "i23a", url: img("1524592094714-0f0654e20314", 1100), alt: "Luxury watch" }],
    location: "Djibouti City Centre",
    condition: "used",
    sellerId: "s5",
    createdAt: daysAgo(1),
    featured: true,
    views: 1020,
    favorites: 88,
    tags: ["watch", "fashion", "luxury"],
    reviews: [dotReview("r8", "Omar", 5, 2, "Beautiful watch, exactly as shown.")],
    status: "active",
  },
  {
    id: "l24",
    title: "Nike Air Jordan High Top – Size 42",
    description:
      "Authentic Nike Air Jordan high-tops, size 42. Worn twice, very clean, original box. Premium streetwear sneakers.",
    price: 62000,
    category: "buy-sell",
    kind: "products",
    images: [{ id: "i24a", url: img("1542291026-7eec264c27ff", 1100), alt: "Nike sneakers" }],
    location: "Djibouti City",
    condition: "used",
    sellerId: "s5",
    createdAt: daysAgo(5),
    views: 540,
    favorites: 63,
    tags: ["shoes", "sneakers", "nike"],
    reviews: [],
    status: "active",
  },
  {
    id: "l25",
    title: "Designer Leather Handbag – New",
    description:
      "High-quality Italian leather handbag, caramel colour, gold hardware. Perfect for office or evening. Comes with dust bag.",
    price: 48000,
    category: "buy-sell",
    kind: "products",
    images: [{ id: "i25a", url: img("1553062407-98eeb64c6a62", 1100), alt: "Designer handbag" }],
    location: "Djibouti City Centre",
    condition: "new",
    sellerId: "s5",
    createdAt: daysAgo(3),
    views: 480,
    favorites: 39,
    tags: ["fashion", "bag", "leather"],
    reviews: [],
    status: "active",
  },

  // ---------- Agriculture ----------
  {
    id: "l26",
    title: "Tractor – 4WD, 60HP",
    description:
      "Used 60HP 4WD tractor in very good condition. Recent service, new hydraulic system and PTO. Ideal for farms in Ali Sabieh and Dikhil.",
    price: 3500000,
    category: "buy-sell",
    kind: "products",
    images: [{ id: "i26a", url: img("1591857177580-dc82b9ac4e1e", 1100), alt: "Farm tractor" }],
    location: "Ali Sabieh",
    condition: "used",
    sellerId: "s7",
    createdAt: daysAgo(7),
    views: 620,
    favorites: 36,
    tags: ["agriculture", "tractor", "farm"],
    reviews: [],
    status: "active",
  },
  {
    id: "l27",
    title: "He-goats for sale – 20 head",
    description:
      "Healthy local he-goats for sale, vaccinated and well fed. Great for meat or breeding. Price per head; discounts for bulk.",
    price: 18000,
    priceLabel: "per head",
    category: "buy-sell",
    kind: "products",
    images: [{ id: "i27a", url: img("1548199973-03cce0bbc87b", 1100), alt: "Goats" }],
    location: "Dikhil",
    condition: "used",
    sellerId: "s7",
    createdAt: daysAgo(3),
    views: 360,
    favorites: 15,
    tags: ["agriculture", "animals", "goats"],
    reviews: [],
    status: "active",
  },

  // ---------- Construction ----------
  {
    id: "l28",
    title: "Cement, sand & construction materials",
    description:
      "Wholesale construction materials: cement (50kg), sand, gravel, rebar and blocks. Best prices for builders and contractors in Djibouti City.",
    price: 2500,
    priceLabel: "per bag",
    category: "buy-sell",
    kind: "products",
    images: [{ id: "i28a", url: img("1541888946425-d81bb19240f5", 1100), alt: "Construction materials" }],
    location: "Djibouti City",
    condition: "new",
    sellerId: "s6",
    createdAt: daysAgo(2),
    views: 470,
    favorites: 18,
    tags: ["construction", "cement", "materials"],
    reviews: [],
    status: "active",
  },

  // ---------- Services ----------
  {
    id: "l29",
    title: "Electrician – Home & Commercial",
    description:
      "Certified electrician for installations, rewiring, lighting, solar panels and emergency repairs. 12 years experience. Fast response in Djibouti City.",
    price: 5000,
    priceLabel: "per hour",
    category: "services",
    kind: "services",
    images: [{ id: "i29a", url: img("1621905251189-08b45d6a269e", 1100), alt: "Electrician at work" }],
    location: "Djibouti City",
    condition: "service",
    sellerId: "s6",
    createdAt: daysAgo(1),
    featured: true,
    views: 1340,
    favorites: 120,
    tags: ["electricity", "repair", "solar"],
    service: { duration: "1 hour", type: "Home service", experienceYears: 12 },
    reviews: [
      dotReview("r9", "Rachid", 5, 1, "Very professional and fast."),
      dotReview("r10", "Amina", 5, 8, "Fixed everything in one visit."),
    ],
    status: "active",
  },
  {
    id: "l30",
    title: "Plumber – Leaks, Bathrooms & Kitchens",
    description:
      "Experienced plumber for all water installations, leaks, pipework, water heaters and complete bathroom renovations. Available every day.",
    price: 4500,
    priceLabel: "per hour",
    category: "services",
    kind: "services",
    images: [{ id: "i30a", url: img("1585128792020-803d29415281", 1100), alt: "Plumber working" }],
    location: "Djibouti City",
    condition: "service",
    sellerId: "s6",
    createdAt: daysAgo(4),
    views: 780,
    favorites: 54,
    tags: ["plumbing", "repair", "bathroom"],
    service: { duration: "1 hour", type: "Home service", experienceYears: 8 },
    reviews: [],
    status: "active",
  },
  {
    id: "l31",
    title: "Construction Team – Renovation & Building",
    description:
      "Full construction team for renovation, painting, tiling, roofing and small building projects. Free quotation and project management.",
    price: 350000,
    priceLabel: "per project",
    category: "services",
    kind: "services",
    images: [{ id: "i31a", url: img("1517581177682-a085bb7ffb15", 1100), alt: "Construction team" }],
    location: "Djibouti City",
    condition: "service",
    sellerId: "s6",
    createdAt: daysAgo(6),
    views: 690,
    favorites: 43,
    tags: ["construction", "renovation", "painting"],
    service: { duration: "per project", type: "Project", experienceYears: 10 },
    reviews: [dotReview("r11", "Hamad", 5, 4, "Great work on our renovation.")],
    status: "active",
  },
  {
    id: "l32",
    title: "Car Mechanic – Mobile Workshop",
    description:
      "Mobile mechanic for engine, brakes, clutch and AC repairs. We come to your home or office in Djibouti City. Genuine spare parts available.",
    price: 6000,
    priceLabel: "per hour",
    category: "services",
    kind: "services",
    images: [{ id: "i32a", url: img("1486262715619-67b85e0b08d3", 1100), alt: "Car mechanic" }],
    location: "Balbala",
    condition: "service",
    sellerId: "s4",
    createdAt: daysAgo(2),
    views: 620,
    favorites: 39,
    tags: ["mechanic", "repair", "mobile"],
    service: { duration: "1 hour", type: "Mobile service", experienceYears: 9 },
    reviews: [],
    status: "active",
  },
  {
    id: "l33",
    title: "French Teacher – Private & Group Lessons",
    description:
      "Native speaker with 6 years experience. French lessons for adults, students and professionals. Online or in person, flexible schedule.",
    price: 3000,
    priceLabel: "per hour",
    category: "services",
    kind: "services",
    images: [{ id: "i33a", url: img("1503676260728-1c00da094a0b", 1100), alt: "Teacher in classroom" }],
    location: "Djibouti City",
    condition: "service",
    sellerId: "s3",
    createdAt: daysAgo(5),
    views: 410,
    favorites: 21,
    tags: ["education", "french", "teacher"],
    service: { duration: "1 hour", type: "Education", experienceYears: 6 },
    reviews: [],
    status: "active",
  },
  {
    id: "l34",
    title: "Brand Design & Website Package",
    description:
      "Logo, brand identity and responsive website for your business. Includes design, development, Google Maps and WhatsApp integration. Delivered in 2-3 weeks.",
    price: 150000,
    priceLabel: "per project",
    category: "services",
    kind: "services",
    images: [{ id: "i34a", url: img("1521737711867-e3b97375f902", 1100), alt: "Designer working" }],
    location: "Remote / Djibouti",
    condition: "service",
    sellerId: "s8",
    createdAt: daysAgo(3),
    featured: true,
    views: 890,
    favorites: 72,
    tags: ["design", "web", "branding", "freelance"],
    service: { duration: "2-3 weeks", type: "Digital", experienceYears: 5 },
    reviews: [dotReview("r12", "Djibouti Coffee", 5, 1, "Amazing branding and fast delivery.")],
    status: "active",
  },
  {
    id: "l35",
    title: "Event & Boat Rental – Celebration Package",
    description:
      "Rent boats and event spaces for celebrations, tours and company gatherings. Catering and photography available. Prices depend on package.",
    price: 120000,
    priceLabel: "per event",
    category: "services",
    kind: "rentals",
    images: [{ id: "i35a", url: img("1569263979104-865ab7cd8d13", 1100), alt: "Boat" }],
    location: "Djibouti City",
    condition: "for-rent",
    sellerId: "s2",
    createdAt: daysAgo(9),
    views: 520,
    favorites: 30,
    tags: ["events", "boat", "celebration"],
    service: { duration: "per event", type: "Rental", experienceYears: 4 },
    reviews: [],
    status: "active",
  },
  {
    id: "l36",
    title: "Camera & Equipment Rental – Photo/Video",
    description:
      "Rent DSLR cameras, lenses, tripods and lighting for events, shoots and projects. Daily and weekly rates. Small deposit required.",
    price: 12000,
    priceLabel: "per day",
    category: "services",
    kind: "rentals",
    images: [{ id: "i36a", url: img("1516035069371-29a1b244cc32", 1100), alt: "Camera equipment" }],
    location: "Djibouti City",
    condition: "for-rent",
    sellerId: "s8",
    createdAt: daysAgo(8),
    views: 460,
    favorites: 27,
    tags: ["rental", "camera", "equipment"],
    service: { duration: "per day", type: "Rental", experienceYears: 3 },
    reviews: [],
    status: "active",
  },
];

export const CATEGORY_COUNT: Record<string, number> = LISTINGS.reduce(
  (acc, l) => {
    acc[l.category] = (acc[l.category] || 0) + 1;
    return acc;
  },
  {} as Record<string, number>
);

export function getSeller(id: string): Seller {
  return SELLERS.find((s) => s.id === id) ?? SELLERS[0];
}

export function getListing(id: string): Listing | undefined {
  return LISTINGS.find((l) => l.id === id);
}

export function formatPrice(value: number): string {
  if (value >= 1_000_000) {
    const m = value / 1_000_000;
    return `${Number.isInteger(m) ? m.toFixed(0) : m.toFixed(1)}M`;
  }
  if (value >= 1_000) {
    return `${(value / 1_000).toFixed(value % 1000 === 0 ? 0 : 1)}K`;
  }
  return `${value}`;
}

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: "c1",
    participant: "Ayan Auto Djibouti",
    participantAvatar: av("Ayan Auto"),
    listingId: "l1",
    listingTitle: "Toyota Land Cruiser Prado 2019",
    createdAt: daysAgo(1),
    unread: 2,
    messages: [
      {
        id: "m1",
        from: "them",
        kind: "text",
        text: "Hello! I saw you liked the Prado. Would you like to book a test drive?",
        at: daysAgo(1),
        status: "read",
      },
      {
        id: "m2",
        from: "them",
        kind: "text",
        text: "It is still available, and we can help with financing.",
        at: daysAgo(1),
        status: "read",
      },
    ],
  },
  {
    id: "c2",
    participant: "Horizon Immobilier",
    participantAvatar: av("Horizon Immobilier"),
    listingId: "l10",
    listingTitle: "Apartment for Rent – Djibouti City Centre",
    createdAt: daysAgo(3),
    unread: 0,
    messages: [
      {
        id: "m3",
        from: "me",
        kind: "text",
        text: "Bonjour, is the apartment still available?",
        at: daysAgo(3),
        status: "read",
      },
      {
        id: "m4",
        from: "them",
        kind: "text",
        text: "Yes, it is. We can arrange a visit this week.",
        at: daysAgo(3),
        status: "read",
      },
    ],
  },
];
